### ISSUE TITLE
All widgets example crashes Python, Windows 10

### ISSUE THREAD

**Issue by cspain** [alfiopuglisi/guietta#13]
The following example causes Python to crash on Windows 10 19041 running Python 3.8.3.

The GUI displays correctly, but when an attempt is made to place the mouse over it, it locks up and Windows offers to close it as Not Responding.

```
Here is the complete widget set:

from guietta import Gui, B, E, L, HS, VS, HSeparator, VSeparator
from guietta import Yes, No, Ok, Cancel, Quit, _, ___, III

gui = Gui(

   [ '<center>A big GUI with all of Guietta''s widgets</center>'],
   [ HSeparator ],

  [ 'Label'    , 'imagelabel.jpeg' , L('another label')  , VS('slider1')],
  [  _         ,     ['button']    , B('another button') ,     III      ],
  [ '__edit__' ,  E('an edit box') , _                   ,   VSeparator ],
  [   Quit     ,        Ok         , Cancel              ,     III      ],
  [    Yes     ,        No         , _                   ,     III      ],
  [  HS('slider2'),    ___         , ___                 ,      _       ] )


gui.show()

```

**Comment by alfiopuglisi** [comment]
Hello @cspain , maybe you have an old version of that example, the last instruction is "gui.show()", while it should be "gui.run()".  show() just shows the window and does not start the event loop.
The old "all.py" example used "dummy = gui.get()", which does basically the same thing. This example has been updated in the meantime.
Please try to change the last line and see it if works better

**Comment by cspain** [comment]
I replaced gui.show() with gui.run() and it now works. Thank you!
