### ISSUE TITLE
"title" not implemented in pip-available egg

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [alfiopuglisi/guietta#18]
First, I have to say that I love guietta. It indeed makes simple GUIs simple. Yay! I know past jobs that I would have done with it, had it existed earlier. Some of my future jobs will use it I guess!

# Documentation says

On https://guietta.readthedocs.io/en/latest/index.html#installation says:

```bash
pip install guietta
```

and on https://guietta.readthedocs.io/en/latest/reference.html#guietta.Gui

`class guietta.Gui(*lists, images_dir='.', create_properties=True, exceptions=<Exceptions.POPUP: 3>, persistence=1, title='')`

Notice that all pages there mention "guietta 0.3.4 documentation".

# Steps to reproduce (here we go!)

## Install guietta

Following https://guietta.readthedocs.io/en/latest/index.html#installation :

```bash
pip install guietta

Collecting guietta
  Using cached guietta-0.3.4-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: PySide2 in _someplace_ (from guietta) (5.15.0)
Requirement already satisfied: shiboken2==5.15.0 in _someplace_ (from PySide2->guietta) (5.15.0)
Installing collected packages: guietta
Successfully installed guietta-0.3.4
```

## Have some code

Create this file `test.py`:

```python
from guietta import Gui

gui = Gui(
    [ 'test' ]
)

gui2 = Gui(
    [ 'test' ],
    title="foo"
)
```

## Run it, fail

```bash
python test.py 

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    gui2 = Gui(
TypeError: __init__() got an unexpected keyword argument 'title'
(python) 
```

## Workaround

```bash
git clone https://github.com/alfiopuglisi/guietta
cd guietta
pip install -e $PWD

Obtaining file:///_someplace_
Requirement already satisfied: PySide2 in _someplace_ (from guietta==0.3.4) (5.15.0)
Requirement already satisfied: shiboken2==5.15.0 in _someplace_ (from PySide2->guietta==0.3.4) (5.15.0)
Installing collected packages: guietta
  Attempting uninstall: guietta
    Found existing installation: guietta 0.3.4
    Uninstalling guietta-0.3.4:
      Successfully uninstalled guietta-0.3.4
  Running setup.py develop for guietta
Successfully installed guietta
```

Then back to previous directory:

```
python test.py
```

No error!

## Summary

* The version 0.3.4 available via pip install does not implement title. Fine.
* The version 0.3.4 tagged in git also does not implement title. Fine.

There are two problems.

* Problem 1: the version of guietta available via the method stated in documentation ( `pip install guietta`) does not match the documentation content.
* Problem 2: online documentation https://guietta.readthedocs.io/en/latest/reference.html#guietta.Gui claims it documents 0.3.4 but it's false, as it documents `title` which is not in [0.3.4](https://github.com/alfiopuglisi/guietta/tree/v0.3.4) and was added [two commits later](https://github.com/alfiopuglisi/guietta/commit/589e37cf1ac873015183be1c9f136b033a137fe5).

## Why is this important?

I can't publish code that relies on `title` feature and `pip install guietta`, it will break for users.

## Suggestion

Three steps:

1. Make a consistent process by which tagging a version and pushing to readthedocs is the same process (one can't be done separated from the other). I would write a local makefile but perhaps a github automation of some sort is a possible alternative.
1. Tag current master as 0.3.5, updating the docs at the same time.
1. Users are happy with guietta! Well, at least this issue is closed!

Thanks!

**Comment by alfiopuglisi** [comment]
Hello Stéphane, thanks for the detailed report. I realize only now that the online documentation is newer than what is published on pip, because it follows the github commits. I will try to setup a consistent process as you say. I hope to do this within this week

**Comment by amrrs** [comment]
@fidergo-stephane-gourichon I came here to see the title and just wanted to express my THanks to you for such a detailed feedback and report! 🙏🏽

**Comment by alfiopuglisi** [comment]
Documentation on readthedocs is now versioned, thanks @fidergo-stephane-gourichon for pointing out this problem, which could have got out of hand after a while :)
