### ISSUE TITLE
How to package and distribute ?

### ISSUE THREAD

**Issue by odeckmyn** [alfiopuglisi/guietta#19]
How can we package and distribute the app made with guietta ? 

I was able to build a GUI in no more than 2 hours, this is incredible, thks !!!!

Now we need to build a binary (for OSX) and distribute to our (internal) users.

Thanks

**Comment by odeckmyn** [comment]
that was super easy, too : 
https://doc.qt.io/qtforpython/deployment-pyinstaller.html

**Comment by alfiopuglisi** [comment]
Hello @odeckmyn, good that you found something that works! I might even mention it in the tutorial. Since it is advice that comes directly from QT, I guess that it can be trusted :)
