### ISSUE TITLE
How to I use RadioButtons?

### ISSUE THREAD

**Issue by shubham0204** [alfiopuglisi/guietta#20]
I have implemented three radio buttons with guietta like,

```
from guietta import _ , Gui , Quit , R1 , R2 , R3

app = Gui(
    [ R1( "r1") , R1( "r2" ) , R1( "r3" ) ],
)
```

How do I check whether which radio button is checked by the user? How do I listen for click events for radio buttons?

**Comment by alfiopuglisi** [comment]
Have a look at the radio.py examples (in the guietta/examples directory on
github), it shows two or three different methods to listen for events. I
updated the example on github to also show how a particular radio button is
checked.

**Comment by shubham0204** [comment]
Ok, I was able to solve my issue. Thanks! Guietta is amazing!
