### ISSUE TITLE
Can I use QFileDialog in guietta?

### ISSUE THREAD

**Issue by bjmiao** [alfiopuglisi/guietta#23]
I need to use QFileDialog in my app. However it needs a handle to call the QFileDialog. How can I access the  Qt handle of a Gui instance?

**Comment by bjmiao** [comment]
By checking the source code I found that it is possible to use it in the following way:

`
from guietta import QFileDialog
filename = QFileDialog.getOpenFileName(None, "Open File",
                                            "./",
                                            "All(*.*)")
print(filename)
`

**Comment by alfiopuglisi** [comment]
Right. I added a note on this in the docs (visible at https://guietta.readthedocs.io/en/latest/ )
