### ISSUE TITLE
Unable to run Guietta when using pyinstaller if ___ is used.

### ISSUE THREAD

**Issue by arcsi05** [alfiopuglisi/guietta#25]
# Steps to reproduce:
1. Use ___ (three underscores - Horizontal widget span) in your GUI
2. Run pyinstaller with your .py file ```pyinstaller app.py --name=MyApp```
3. Launching the .exe file gives error
## Error message:
```
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    some_gui = Gui(['status', ___],
  File "lib\site-packages\guietta\guietta.py", line 1509, in __init__
IndexError: ___ at the beginning of a row
[13116] Failed to execute script app
```
# Workaround
To workaround this issue, you can replace all ___ (three underscores - Horizontal widget span) with something else. Your GUI will not look the same, but after running pyinstaller again, the application works.

## Possible solution
Possible solution would be to replace the ___ (three underscores) with some other set of characters (for example: HHH).

**Comment by alfiopuglisi** [comment]
Thanks for the report, unfortunately I cannot reproduce the problem. Using this code:
`from guietta import Gui, ___`
`some_gui = Gui(['status', ___])`
`some_gui.run()`

it works even with pyinstaller.
Can you please give some more information? Python version, OS version, PyInstaller version, etc?

**Comment by arcsi05** [comment]
thanks for the reply. I have no idea what happened, but now it works for me as well...
