### ISSUE TITLE
Guietta :ValueError: Could not determine the Gui instance identifier

### ISSUE THREAD

**Issue by mahanthkj** [alfiopuglisi/guietta#26]
Python version used : 3.7

kindly help to resolve this issue.
script :
from guietta import _, Gui, Quit

gui = Gui(

[ 'Enter numbers:', 'a' , '+' , 'b', ['Calculate'] ],
[ 'Result: -->' , 'result' , _ , _ , _ ],
[ _ , _ , _ , _ , Quit ]
)

with gui.Calculate:
gui.result = gui.a + gui.b

gui.run()

### **Error:**

C:\Users\labuser\Downloads\temp>python cguietta.py
Traceback (most recent call last):
File "cguietta.py", line 11, in
gui.result = gui.a + gui.b
File "C:\Users\labuser\AppData\Local\Programs\Python\Python37\lib\site-packages\guietta\guietta.py", line 159, in exit
raise ValueError('Could not determine the Gui instance identifier')
ValueError: Could not determine the Gui instance identifier

C:\Users\labuser\Downloads\temp>

**Comment by alfiopuglisi** [comment]
Hello, this bug should be fixed in version 0.3.8. Please try to upgrade to that version and see if it works

**Comment by mahanthkj** [comment]
Wow !! That was a quick Fix . .  Really Appreciate it  .. 
Thank you ..

**Comment by mahanthkj** [comment]
also, i was looking for documentation. i wanted to set the title for gui window.
if you can let me know , where i can find documentation for guietta, it would be helpful

**Comment by alfiopuglisi** [comment]
The documentation is at https://guietta.readthedocs.io/en/stable/index.html
You can set the title, but it's a bit hidden in the documentation :) Have a look at the Gui class definition here: https://guietta.readthedocs.io/en/stable/reference.html#gui-class-reference  you can add a title='mytitle' keyword argument.

**Comment by mahanthkj** [comment]
got the "title" working . . Thanks for your help and Guidance . .
