### ISSUE TITLE
Radio Buttons with spaces in their name have no documented reference style

### ISSUE THREAD

**Issue by jkelowitt** [alfiopuglisi/guietta#27]
Radio Buttons which have spaces in their name, like the first button below, are referred to by the name with no spaces, while keeping the case. This isn't in the documentation.

```python
gui = Gui(
    [R("This is the first Button"), R("second")],
)

with gui.ThisisthefirstButton as a:
    print("Apple", a.isChecked())

with gui.second as b:
    print("Sauce", b.isChecked())
```

Thank you so much for working on this! I like guietta a lot more than tkinter or other gui's.

**Comment by alfiopuglisi** [comment]
It's written somewhere else (in the chapter called "Guietta's magic properties'), but I agree that the documentation could be clearer, I will update it.

**Comment by jkelowitt** [comment]
Ah, I see. That's what I get for not reading the documentation.
