### ISSUE TITLE
Demo_Calculator: How to initialize gui.result

### ISSUE THREAD

**Issue by virbcal** [alfiopuglisi/guietta#29]
Hi!

Operating System:  Windows 8.1
Python version:  Python 3.7.4
guietta Port and Version:  guietta 0.3.8
Code or partial code causing the problem:

# Start of Code
from guietta import _, Gui, Quit
first = True
gui = Gui(
	[ "Enter numbers:",  "__a__", "+", "__b__", ["Calculate"] ],
	[    "Result: -->", "result",   _,       _,             _ ],
	[                _,        _,   _,       _,          Quit ]
)

with gui.Calculate:
	if first:
		first = False
		gui.result = ""
	else:
		gui.result = float(gui.a) + float(gui.b)

gui.run()
# End of Code

Program code: (I could not get the above code to properly indent so I attached the file.)
[gCalculator.txt](https://github.com/alfiopuglisi/guietta/files/5068437/gCalculator.txt)

Screenshots:

First display:
![image](https://user-images.githubusercontent.com/53043163/90122246-9189a400-dd8f-11ea-95b5-0e04e7939fa6.png)

Error message:
![image](https://user-images.githubusercontent.com/53043163/90122354-bd0c8e80-dd8f-11ea-8b93-6210fd572609.png)

Narrative:

The intention is to initialize gui.result to show blank at the first display of the screen instead of showing "result".
The code above worked but upon clicking the "Calculate" button, with or without entries in the two input fields, I get the error:

                  "UnBoundLocalError: local variable 'first' referenced before assignment"

Please tell me how to initialize gui.result without causing any error to the program.

Thank you.

**Comment by alfiopuglisi** [comment]
Hello, unfortunately the "with" syntax is quite limited and referring to variables outside scope (like "first" in you example) can be problematic.
Instead of a global variable, you can use the "gui.is_running" property:
```
with gui.Calculate:
        if not gui.is_running:
                gui.result = ""
        else:
                gui.result = float(gui.a) + float(gui.b)
```
this should work.

**Comment by virbcal** [comment]
Thanks much, it's working now.
