### ISSUE TITLE
NameError: name '_' is not defined

### ISSUE THREAD

**Issue by muchomuchacho** [alfiopuglisi/guietta#3]
Quickly following the docs examples I got the error bellow. I was hoping for those placeholders to be converted to strings automatically but it seems like they aren't in some cases. Perhaps this is a good area to add some unit testing?

```gui.events(

    [  _            ,  _ , _ ,   replot     ],
    [  _            ,  _ , _ ,   _          ],
    [  _            ,  _ , _ ,   _          ], )
```
```
    [  _            ,  _ , _ ,   replot     ],
NameError: name '_' is not defined
```

**Comment by muchomuchacho** [comment]
Nevermind, it seems like I needed to import it: `from guietta import _`. My bad.

**Comment by alfiopuglisi** [comment]
Ok good. I think that the import is it at the beginning of the example in the readme :)
