### ISSUE TITLE
Magic Properties make very long names for labels with HTML tags. 

### ISSUE THREAD

**Issue by jkelowitt** [alfiopuglisi/guietta#31]
HTML can be used to enhance labels in the gui. For example, the following gui:
```python
from guietta import Gui

gui = Gui(
    ["a boring, normal label"],
    ["<p style='color:red;font-size:20px'><i>Super cool label"]
    )

gui.run()
```
Which produces this gui:
![Ek7VyQ6](https://user-images.githubusercontent.com/58435724/90328524-d52c0b80-df51-11ea-8270-4a880cf3cdff.png)

Guietta's magic properties dutifully gives me two names, one for each of these labels. The first, "aboringnormallabel", and the second, "pstylecolorredfontsize20pxiSupercoollabel". 

"pstylecolorredfontsize20pxiSupercoollabel" is 41 characters long.

 It would be nice to be able to make the magic properties ignore the html tags, or to set the widget name myself.

**Comment by alfiopuglisi** [comment]
It is possible to rename widgets using a 2-elements tuple:

( ["<p style='color:red;font-size:20px'><i>Super cool label"], 'cool_label' )

The magic property will then be _gui.cool_label_

It looks like this is not explained in the tutorial, I will add it.

**Comment by alfiopuglisi** [comment]
Latest release on readthedocs has the additional documentation now. It will go into "stable" with the next release.
