### ISSUE TITLE
HOW TO customize the gui window title?

### ISSUE THREAD

**Issue by virbcal** [alfiopuglisi/guietta#33]
Hi!

Operating System: Windows 8.1
Python version: Python 3.7.4
guietta Port and Version: guietta 0.3.8
Code or partial code causing the problem:

1. How do I customize the window's title? Is there a way to do it without installing PyQt?
2. How do I make row spacing smaller so as not to occupy twice the window space needed?

Thank you.

**Comment by alfiopuglisi** [comment]
Hello,
for the title, it's not very evident in the documentation but the main Gui class has a "title" keyword that can be used to set the window title. Have a look at the "progress_bar_title" example.

For the row spacing, guietta uses a QGridLayout, which has some methods to customize the spacing. You can try the setVerticaSpacing() method:

gui.layout().setVerticalSpacing(0)

more info here: https://doc.qt.io/qt-5/qgridlayout.html

**Comment by virbcal** [comment]
Nice, perfect, it's working, many thanks!
