### ISSUE TITLE
Considering releasing/accepting PR for dedicated builds for Conda? 

### ISSUE THREAD

**Issue by kevin931** [alfiopuglisi/guietta#37]
Given the incompatibility of pip's QT implementation with conda as mentioned by [documentation](https://guietta.readthedocs.io/en/stable/qt_conda.html), will a dedicated build for conda make more sense for other packages to properly depend on guietta? 

**Some reasons why this approach may make sense:**
* https://github.com/ContinuumIO/anaconda-issues/issues/1554 suggests building specifically for conda and using conda dependencies to address the incompatibility since they will not rename pyqt. 
* Other packages do not have to include the incompatibility notice or risk unaware users breaking their conda environments.

**Comment by alfiopuglisi** [comment]
Do you mean a dedicated build of guietta to be used in conda environments? That's a good idea, it would fix the dependency problems as long as one sticks to conda to install files.
I will look into how to do this. Or if you want to try... :)

**Comment by kevin931** [comment]
Yes! That's what I mean! I created PR #38 which should have all the necessary steps to build and upload the package to conda.

**Comment by alfiopuglisi** [comment]
Thanks for the PR, it was a nice Christmas present :)
I was able to install guietta using conda with this command:

conda install -c alfiopuglisi -c conda-forge guietta

Do you think it would be worthwhile to add it to conda-forge too? It would avoid the need using two different channels in the install command. Or is there another way?

**Comment by kevin931** [comment]
Merry Christmas! Thanks for merging the PR. I was glad to help! 

It's a good idea to add it to conda-forge as well (this didn't cross my mind). I admit that working with channels can get a bit inconvenient for end users, and this seems to be the best solution to simplify things for conda. I looked at the [documentation](https://github.com/conda-forge/staged-recipes) for the process, and it looks like it shouldn't too much work to use the existing recipe and create a PR at conda-forge/staged-recipes. They recommend including the LICENCE file with the package, which can be achieved by adding a extra line to the recipe (I can submit another PR for this quick and useful change). If all else goes well, the rest should be automated by conda-forge.

Let me know if there is any way I may help in the process!

**Comment by alfiopuglisi** [comment]
Done, the PR for conda-forge is here: https://github.com/conda-forge/staged-recipes/pull/13554
It was a bit more difficult than expected, because the PySide2 modules want a working display connection when imported, and thus I had to customize the recipe's test section using xvfb (and it wasn't easy to discover, since the tests run in a custom docker image).

**Comment by kevin931** [comment]
Awesome! Thanks again! Closing this...
