### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Switch1024** [alfiopuglisi/guietta#39]
Hello there,
first of all, you did an amazing job with this tool, its really easy to use.
Here are my questions;

1. How can i change the background to a color or image?
2. Can i change the program title somewhere else in the program, or do i have to redraw the screen?
3. Is it possible to open new forms in the main form?

Thanks for reading, and once again good job.

**Comment by alfiopuglisi** [comment]
Most things not handled by guietta can be done with normal QT functions, so usually if you don't know how to do things, look them up in the QT documentation and you will find a way. Just remember that guietta's windows are normal QWidget objects, so:

1) this should work:
gui.window().setStyleSheet('background-color: red')
gui.window().setStyleSheet("background-image: url(./image.png)")

2) not sure I understand your question correctly, if you just mean the window title, you can use the title() method:
gui.title('new title')

3) you can build new Gui instances and call the show() method on them, at this point you should have both windows open and working in parallel. But I haven't experimented much in this direction

**Comment by Switch1024** [comment]
Thanks for responding, sorry for my late response by the way. My notifications don't seem to work. Anyways thanks or your response :)
