### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by Nexuzzzz** [alfiopuglisi/guietta#42]
I just installed Guietta because i got a new pc, and i tried the example but this exception kept appearing

```py
>>> from guietta import _, Gui, Quit
>>> gui = Gui(
... [ "Enter numbers:",  "__a__", "+", "__b__", ["Calculate"] ],
... [    "Result: -->", "result",   _,       _,             _ ],
... [                _,        _,   _,       _,          Quit ]
... )
>>>
>>> with gui.Calculate:
...     gui.result = float(gui.a) + float(gui.b)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __enter__
>>> gui.run()
```

Guietta version is `(0.2.3)`

**Comment by Nexuzzzz** [comment]
Somehow fixed it when i removed and redownloaded Guietta and restarted my system. Weird.

**Comment by Nexuzzzz** [comment]
Error seems to appear when using Python 3.10. If you have this error just use any version below 3.10

**Comment by alfiopuglisi** [comment]
I have just tested guietta with Python 3.10 and it seems to work fine.
Your guietta version is 0.2.3, which is very old. 1.0.0 was just released, and if you prefer version 0.x, it went up to 0.6.1. Can you try to upgrade guietta instead of downgrading Python?

**Comment by Nexuzzzz** [comment]
> I have just tested guietta with Python 3.10 and it seems to work fine. Your guietta version is 0.2.3, which is very old. 1.0.0 was just released, and if you prefer version 0.x, it went up to 0.6.1. Can you try to upgrade guietta instead of downgrading Python?

i update it, and the error went away. Thanks for responding by the way (excuse my VERY late response)
