### ISSUE TITLE
projections in matplotlib widget?

### ISSUE THREAD

**Issue by bigbenhur** [alfiopuglisi/guietta#45]
Hi

Is there a way to create a plot with a projection in guietta, e.g. for a polar or 3d plot?

I believe the corresponding projection keyword has to be supplied to matplotlib's add_subplot, which is currently not implemented in guietta. Maybe one can add the projection keyword to the MatplotlibWidget? It would be quite a simple change to enhance the plot types available. And because the keyword is optional, it would be backward compatible.

Cheers!

**Comment by alfiopuglisi** [comment]
Thanks for the suggestion! I have added a projection keyword to the MatplotlibWidget. It's already on pip as version 1.4.1, see also the plot_projection.py in the examples subdirectory.

**Comment by bigbenhur** [comment]
Wow, fastest feature implementation ever! Tested and it works perfectly, too 😍

Thank you VERY MUCH 🎉
