### ISSUE TITLE
Crash when use setStyleSheet this function in subthread.

### ISSUE THREAD

**Issue by SmildWind** [alfiopuglisi/guietta#47]
I use another thread to change the color of the widgets['result'] ， but I found that the programmer will crash when I change the stylesteet of 'result' 20~120 times.
Maybe this is a multiprocessing problem, the another thread possibly casue some memory error.

Here is a example code:
```
from guietta import _, Gui
import threading
import time
gui = Gui(
    ['result']
)

def startWS():
    while True:
        gui.widgets['result'].setStyleSheet('color:rgb(255, 0, 0);')
        time.sleep(0.1)
        gui.widgets['result'].setStyleSheet('color:rgb(0, 176, 52);')
        time.sleep(0.1)
threading.Thread(target=startWS).start()

gui.run()
```

**Comment by alfiopuglisi** [comment]
guietta is built on top of PyQt, and PyQt does not allow changing widget properties from threads. This is mentioned in the tutorial: 
https://guietta.readthedocs.io/en/latest/tutorial.html#working-with-threads

There is also a decorator, gui.execute_in_main_thread   (see https://guietta.readthedocs.io/en/latest/reference.html ) that can be used to make sure that a function runs in the main thread and can update widgets.

**Comment by SmildWind** [comment]
Thanks a lot ! I have already solved the problem.
