### ISSUE TITLE
Mac Catalina - Result not getting updated 

### ISSUE THREAD

**Issue by amrrs** [alfiopuglisi/guietta#6]
![image](https://user-images.githubusercontent.com/5347322/86480727-3023ed80-bd6c-11ea-932a-90b42fc67ad1.png)

Hey, Thanks for making this. As in the screenshot, the result isn't getting updated. I tried with the calculator example too!

PLease help! 

A

**Comment by rhasoff** [comment]
I'm no expert bu it seems you didn't attached any actions to that go button
Insert this before  gui.run() and try again. 

with gui.Go: 
    gui.result = float(gui.num)


And [here's ](https://guietta.readthedocs.io/en/latest/)  a link to the documentation.

**Comment by alfiopuglisi** [comment]
It looks like you took the first example from the tutorial, which is intentionally simple and does not attach any action to the button. Scroll down to "GUI actions" and it will show you how to add an action.

**Comment by amrrs** [comment]
Shouldn't this one work ? I mean, there's the function `calculate` being triggered or am I still missing?

![image](https://user-images.githubusercontent.com/5347322/86482936-8dba3900-bd70-11ea-8f66-f0cba6d6ee72.png)

**Comment by amrrs** [comment]
Thanks @alfiopuglisi I thought this one should fire up `calculate` and hence the `result` must be updated. But is not working, Am i still missing something?

![image](https://user-images.githubusercontent.com/5347322/86483223-39fc1f80-bd71-11ea-8b98-fd8ae42ff478.png)

**Comment by alfiopuglisi** [comment]
Yes, the function `calculate` should be triggered when you click the Calculate button. The with statement in guietta hides all exceptions, so it's a bit hard to understand what is the problem.
Can you try to use the events layer as described in the tutorial? It should be something like this:

`gui = Gui( [ 'Enter number' , '__num__' , ['Go'] ],`
`                 [ 'Result ---> ' , 'result'  ,   _    ] )`
`gui.events([       _        ,     _     ,  recalc ],`
`                 [       _        ,     _     ,   _     ] )`

`def recalc(gui, *args):`
`    gui.result = float(gui.num)*2`

**Comment by amrrs** [comment]
thanks @alfiopuglisi. I just figured out - ironically when move to a different window (other than the python gui) and come back to python gui, the result gets updated. It's the same case for both examples.I'll close the issue anyways. Please let me know if you know why it is.

**Comment by alfiopuglisi** [comment]
Hi @amrrs, unfortunately I do not know why you have this problem. I see from your screenshots that you are using a Mac, I am getting multiple problem reports from Mac users. I might have to work on this a bit :)

**Comment by amrrs** [comment]
Thanks @alfiopuglisi :)
