### ISSUE TITLE
matplotlib example

### ISSUE THREAD

**Issue by boiled-greggs** [alfiopuglisi/guietta#7]
One of your examples is the `matplotlib.py` script, which of course needs to import matplotlib to function, but can't since the file itself in the examples directory is called `matplotlib.py`.

**Comment by alfiopuglisi** [comment]
True, you run it from the same directory, it screws up the import. Thanks for the heads up, I will rename the file. As a temporary workaround, you can run it from a different directory, for example from the top-level directory, like this: `python -m guietta.examples.matplotlib`  (the dotted path has to match the filesystem path)

**Comment by alfiopuglisi** [comment]
Fixed in commit 2e4c72f
