### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.

### ISSUE THREAD

**Issue by Ajinkz** [alfiopuglisi/guietta#8]
input:
`from guietta import _, Gui, Quit`

output:
```
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.```

**Comment by alfiopuglisi** [comment]
Can happen with some Qt installations. Which Python version are you using? Which OS?
Did you try to follow the steps in https://guietta.readthedocs.io/en/latest/troubleshooting.html ?

**Comment by upgradeQ** [comment]
Ubuntu 20.04 , default python, this worked for me : `sudo apt install libxcb-xinerama0`

**Comment by Ajinkz** [comment]
OS: Windows 10
I tried installing QT platform related installation but still not working

**Comment by alfiopuglisi** [comment]
Hello @Ajinkz , sorry for these problems. I do not have a Windows10 computer to test at the moment, I will try to find one
